% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{caption}
\usepackage{anyfontsize}
\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\@ifpackageloaded{fontawesome5}{}{\usepackage{fontawesome5}}
\definecolor{quarto-callout-color}{HTML}{909090}
\definecolor{quarto-callout-note-color}{HTML}{0758E5}
\definecolor{quarto-callout-important-color}{HTML}{CC1914}
\definecolor{quarto-callout-warning-color}{HTML}{EB9113}
\definecolor{quarto-callout-tip-color}{HTML}{00A047}
\definecolor{quarto-callout-caution-color}{HTML}{FC5300}
\definecolor{quarto-callout-color-frame}{HTML}{acacac}
\definecolor{quarto-callout-note-color-frame}{HTML}{4582ec}
\definecolor{quarto-callout-important-color-frame}{HTML}{d9534f}
\definecolor{quarto-callout-warning-color-frame}{HTML}{f0ad4e}
\definecolor{quarto-callout-tip-color-frame}{HTML}{02b875}
\definecolor{quarto-callout-caution-color-frame}{HTML}{fd7e14}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Report on the use of passive acoustic monitoring in Prince Edward Island National Park},
  pdfauthor={Alex MacPhail},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Report on the use of passive acoustic monitoring in Prince Edward
Island National Park}
\author{Alex MacPhail}
\date{2026-04-29}
\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{3}
\tableofcontents
}

\begin{center}
\pandocbounded{\includegraphics[keepaspectratio]{assets/peinpheader.png}}
\end{center}

\section{Abstract}\label{abstract}

Passive acoustic monitoring has proven to be a valuable tool for
monitoring vocalizing species. Environmental sensors are becoming
increasingly easy to program and can autonomously generating extensive
data sets of the soundscape, an invaluable resource for ecological
integrity monitoring. Prince Edward Island National deployed autonomous
recording units (ARUs) across 43 locations during a comprehensive 7-year
survey. ARUs detected a total of 102 species including birds, amphibians
and mammals. The analysis revealed that songbird species richness and
diversity remained relatively stable, while single-species occupancy at
individual sites exhibited diverse patterns. Common and generalist
species showed consistent occupancy despite large sources of natural and
anthropogenic disturbance. Ongoing monitoring and dynamic models can
yield more detailed and predictive results to ensure the continued
maintenance of ecological integrity in the Park.

\begin{tcolorbox}[enhanced jigsaw, opacitybacktitle=0.6, leftrule=.75mm, toptitle=1mm, breakable, opacityback=0, rightrule=.15mm, left=2mm, arc=.35mm, coltitle=black, colback=white, colframe=quarto-callout-note-color-frame, colbacktitle=quarto-callout-note-color!10!white, bottomtitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Note}, bottomrule=.15mm, toprule=.15mm]

This report is dynamically generated, meaning its results may evolve
with the addition of new data or further analyses. For the most recent
updates, refer to the publication date and feel free to reach out to the
authors.

\end{tcolorbox}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Land Acknowledgement}\label{land-acknowledgement}

In the spirit of Reconciliation, wen acknowledge that the land upon
which this data was gathered is unceeded Mi'kmaq territory. Epekwitk
(Prince Edward Island), Mi'kma'ki, is covered by the historic Treaties
of Peace and Friendship. We pay our respects to the Indigenous Mi'kmaq
People who have occupied this Island for over 12,000 years; past,
present and future.

\section{Introduction}\label{introduction}

Human activities have been identified as key pressures and contributors
to the global decline in forest wildlife (Allan et al. (2017)). The
repercussions of habitat fragmentation (Fahrig (2003)) and loss (Hanski
(2011)), climate change (Mantyka-pringle, Martin, and Rhodes (2012),
Sattar et al. (2021), Abrahms et al. (2023)), and increased access to
sensitive areas exert direct and indirect pressures on forest
biodiversity, particularly in managed regions in Canada (Lemieux et al.
(2011)).

In 2019, Prince Edward Island National Park initiated a program
incorporating autonomous recording units (ARUs) for passive acoustic
monitoring (PAM) of the Park's wildlife. ARUs are compact environmental
sensors that are designed to passively record the environment (Shonfield
and Bayne (2017)), capturing vocalizing species like birds and
amphibians, which is growing in use across the globe (Sugai et al.
(2018)). This technology enables resource managers to conduct prolonged
surveys with minimal human interference. The subsequent data collected
by these units contribute valuable information to ecological integrity
metrics such as species richness, diversity, occupancy, and trends over
time. This data aids decision-making and management within the Park.
Given the rapid and ease of accumulating data from these units,
maintaining a high standard of data integrity is paramount to ensure
future data interoperability and sharing.
\href{https://www.wildtrax.ca}{WildTrax} is an online platform developed
by the \href{https://abmi.ca}{Alberta Biodiversity Monitoring Institute
(\textbf{ABMI})} for users of environmental sensors to help addresses
these big data challenges by providing solutions to standardize,
harmonize, and share data.

The objectives of this report are to:

\begin{itemize}
\tightlist
\item
  Describe the data management and processing procedures for the
  acoustic data collected from 2019 to 2025;
\item
  Utilize traditional human tagging, visual scanning and automated
  recognition techniques to detect and count species and individuals
  heard on recordings;
\item
  Define straightforward methods for evaluating species presence,
  species richness, and species occupancy over time at various
  locations;
\item
  Assess the potential of ARUs to detect roosting-associated Bank
  Swallow activity at pond sites within PEINP, including the timing,
  call frequency, and configuration effects across monitoring years;
\item
  Offer recommendations for ongoing monitoring approaches, including ARU
  deployment configurations and scheduling, to contribute to the
  assessment of ecological integrity in forest and wetland ecosystems;
\item
  Facilitate data publication to the public, resource managers, academic
  institutions, and any other relevant agencies
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Methods}\label{methods}

\subsection{Data collection}\label{data-collection}

Data were collected during the spring and summer seasons from 2019 to
2025. A total of 43 locations were surveyed over the seven-year period:

\begin{itemize}
\tightlist
\item
  29 locations as part of the forest songbird monitoring program (code:
  \texttt{PENP-*}) with ARUs recording during the morning hours,
\item
  6 for Bank Swallow Monitoring (code: \texttt{PENP-BS-*} and
  \texttt{BANS-*}) with ARUs placed strategically beside ponds recording
  in the evening,
\item
  2 locations deployed in First Nations communities
  (\texttt{ASC-1,\ LXI-1}) to complement the forest songbird and evening
  schedules,
\item
  And one location (\texttt{PENP-E1}), which was to examine the effects
  of a single public event
\end{itemize}

Locations were surveyed on rotation with 4 locations (PENP-3-1,
PENP-3-4, PENP-3-6, PENP-4-2) surveyed each year. A detailed list of all
survey years can be found in Table 1 (Table~\ref{tbl-loc-summary}) and
illustrated in Figure 1 (Figure~\ref{fig-aru-monitoring-locations}).
ARUs were deployed at the beginning of the breeding season in April-May,
and rotated locations until their final retrieval in July-August. At the
forest songbird locations (\texttt{PENP-*}), the ARUs were set to record
for 30 minutes continuously every hour for four hours, starting one hour
before dawn and ending three hours after dawn. For Bank Swallow
Monitoring locations (\texttt{PENP-BS},\texttt{BANS-}), recordings were
made every 5 minutes for a duration of 3 minutes each from 1.5 hours
before dusk to 1.5 hours after dusk. On average, each ARU recorded for

\begin{figure}

\centering{

\includegraphics[width=3.31in,height=\textheight,keepaspectratio]{map_aru_locations.png}

}

\caption{\label{fig-aru-monitoring-locations}Locations from Prince
Edward Island National Park ARU Monitoring Program}

\end{figure}%

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1048}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0476}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0476}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0476}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0476}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0476}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0476}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0476}}
  >{\raggedright\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.2476}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1429}}
  >{\raggedright\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1714}}@{}}

\caption{\label{tbl-loc-summary}Locations surveyed across years. Ones
indicated a deployment in that year for that location}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Location
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2019
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2020
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2021
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2022
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2023
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2024
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
2025
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Site
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
years\_surveyed
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
survey\_coverage
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
PENP-1-1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & Cavendish & 7 & Full Survey \\
PENP-1-2 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & Cavendish & 7 & Full Survey \\
PENP-1-3 & 1 & 0 & 1 & 1 & 0 & 0 & 0 & Cavendish & 3 & Some Years \\
PENP-2-3 & 1 & 1 & 1 & 1 & 1 & 0 & 0 & Brackley & 5 & Majority of
Years \\
PENP-3-1 & 1 & 1 & 1 & 1 & 1 & 1 & 0 & Dalvay & 6 & Majority of Years \\
PENP-3-2 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & Dalvay & 7 & Full Survey \\
PENP-3-4 & 1 & 0 & 1 & 1 & 1 & 1 & 1 & Dalvay & 6 & Majority of Years \\
PENP-4-1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & Greenwich & 7 & Full Survey \\
PENP-4-2 & 1 & 1 & 1 & 1 & 1 & 0 & 1 & Greenwich & 6 & Majority of
Years \\
PENP-4-3 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & Greenwich & 7 & Full Survey \\
PENP-4-4 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & Greenwich & 7 & Full Survey \\
PENP-1-4 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & Cavendish & 4 & Majority of
Years \\
PENP-3-5 & 0 & 1 & 1 & 1 & 1 & 0 & 0 & Dalvay & 4 & Majority of Years \\
PENP-3-6 & 0 & 1 & 1 & 1 & 1 & 1 & 1 & Dalvay & 6 & Majority of Years \\
ASC-1 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & First Nations Communities & 1 &
Single Year \\
LXI-1 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & First Nations Communities & 1 &
Single Year \\
PENP-1-5 & 0 & 0 & 1 & 1 & 1 & 1 & 1 & Cavendish & 5 & Majority of
Years \\
PENP-1-6 & 0 & 0 & 1 & 1 & 1 & 1 & 1 & Cavendish & 5 & Majority of
Years \\
PENP-3-7 & 0 & 0 & 1 & 1 & 1 & 0 & 0 & Dalvay & 3 & Some Years \\
PENP-3-8 & 0 & 0 & 1 & 1 & 1 & 0 & 0 & Dalvay & 3 & Some Years \\
PENP-4-6 & 0 & 0 & 1 & 1 & 1 & 0 & 0 & Greenwich & 3 & Some Years \\
PENP-5-1 & 0 & 0 & 1 & 1 & 1 & 0 & 0 & Skmaqn & 3 & Some Years \\
PENP-BS-1 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & Bank Swallow Monitoring & 2 &
Some Years \\
PENP-BS-2 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & Bank Swallow Monitoring & 1 &
Single Year \\
PENP-BS-3 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & Bank Swallow Monitoring & 1 &
Single Year \\
PENP-BS-4 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & Bank Swallow Monitoring & 1 &
Single Year \\
PENP-BS-5 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & Bank Swallow Monitoring & 1 &
Single Year \\
PENP-4-5 & 0 & 0 & 0 & 1 & 1 & 0 & 0 & Greenwich & 2 & Some Years \\
PENP-E1 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & Skmaqn & 1 & Single Year \\
PENP-BS-6 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & Bank Swallow Monitoring & 1 &
Single Year \\
PENP-1-7 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & Cavendish & 2 & Some Years \\
PENP-1-8 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & Cavendish & 2 & Some Years \\
PENP-2-4 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & Brackley & 2 & Some Years \\
PENP-3-9 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & Dalvay & 2 & Some Years \\
PENP-4-7 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & Greenwich & 1 & Single Year \\
PENP-4-8 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & Greenwich & 2 & Some Years \\
PENP-5-2 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & Skmaqn & 2 & Some Years \\
PENP-6-1 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & North Rustico & 2 & Some Years \\
BANS-BOW-E & 0 & 0 & 0 & 0 & 0 & 0 & 1 & Bank Swallow Monitoring & 1 &
Single Year \\
BANS-BOW-N & 0 & 0 & 0 & 0 & 0 & 0 & 1 & Bank Swallow Monitoring & 1 &
Single Year \\
BANS-BOW-W & 0 & 0 & 0 & 0 & 0 & 0 & 1 & Bank Swallow Monitoring & 1 &
Single Year \\
PENP-3-1Z & 0 & 0 & 0 & 0 & 0 & 0 & 1 & Dalvay & 1 & Single Year \\
PENP-4-9 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & Greenwich & 1 & Single Year \\

\end{longtable}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1392}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.3038}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1013}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1266}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1139}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0886}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0633}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0633}}@{}}

\caption{\label{tbl-obvs-and-covs}Site covariates for each forest
songbird monitoring (PENP-*) location. Landcover is measured as
proportion cover at 150 meter radius surrounding the ARU categorized
into anthropogenic (pavement, soy), open (grass, sand dune, bare soil),
deciduous (red maple, white birch, alder, poplar) and conifer (white
spruce, black spruce, balsam fir) and wetlands.}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
location
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Distance from coast (m)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Conifer
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Deciduous
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Wetlands
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Anthro
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Open
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
NA
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
BANS-BOW-E & 546.24 & 0.06 & 0.01 & 0.93 & 0.00 & 0.00 & 0.00 \\
BANS-BOW-N & 166.77 & 0.00 & 0.00 & 1.00 & 0.00 & 0.00 & 0.00 \\
BANS-BOW-W & 456.45 & 0.00 & 0.07 & 0.93 & 0.00 & 0.00 & 0.00 \\
PENP-1-1 & 843.54 & 0.00 & 0.04 & 0.00 & 0.83 & 0.13 & 0.00 \\
PENP-1-2 & 428.46 & 0.95 & 0.00 & 0.04 & 0.01 & 0.00 & 0.00 \\
PENP-1-3 & 1609.91 & 0.85 & 0.03 & 0.00 & 0.03 & 0.09 & 0.00 \\
PENP-1-4 & 106.02 & 0.91 & 0.00 & 0.09 & 0.00 & 0.00 & 0.00 \\
PENP-1-5 & 2147.58 & 0.08 & 0.92 & 0.00 & 0.00 & 0.01 & 0.00 \\
PENP-1-6 & 1695.94 & 0.03 & 0.00 & 0.00 & 0.00 & 0.97 & 0.00 \\
PENP-1-7 & 655.50 & 0.20 & 0.44 & 0.00 & 0.18 & 0.18 & 0.00 \\
PENP-1-8 & 476.88 & 0.45 & 0.08 & 0.00 & 0.05 & 0.43 & 0.00 \\
PENP-2-3 & 114.49 & 0.39 & 0.42 & 0.08 & 0.02 & 0.08 & 0.00 \\
PENP-2-4 & 324.50 & 0.21 & 0.66 & 0.00 & 0.07 & 0.06 & 0.00 \\
PENP-3-1 & 971.57 & 0.21 & 0.07 & 0.29 & 0.00 & 0.00 & 0.43 \\
PENP-3-1Z & 967.25 & 0.27 & 0.03 & 0.27 & 0.00 & 0.00 & 0.44 \\
PENP-3-2 & 664.74 & 0.14 & 0.35 & 0.10 & 0.00 & 0.00 & 0.42 \\
PENP-3-4 & 378.32 & 0.24 & 0.44 & 0.32 & 0.00 & 0.00 & 0.00 \\
PENP-3-5 & 66.67 & 0.36 & 0.05 & 0.49 & 0.10 & 0.00 & 0.00 \\
PENP-3-6 & 1243.54 & 0.55 & 0.45 & 0.00 & 0.00 & 0.00 & 0.00 \\
PENP-3-7 & 424.88 & 0.34 & 0.00 & 0.00 & 0.56 & 0.10 & 0.00 \\
PENP-3-8 & 107.72 & 0.48 & 0.00 & 0.13 & 0.04 & 0.35 & 0.00 \\
PENP-3-9 & 785.01 & 0.45 & 0.00 & 0.49 & 0.04 & 0.01 & 0.00 \\
PENP-4-1 & 431.00 & 0.34 & 0.41 & 0.25 & 0.00 & 0.00 & 0.00 \\
PENP-4-2 & 726.48 & 0.40 & 0.55 & 0.00 & 0.00 & 0.05 & 0.00 \\
PENP-4-3 & 1260.58 & 0.68 & 0.00 & 0.32 & 0.00 & 0.00 & 0.00 \\
PENP-4-4 & 544.80 & 1.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
PENP-4-5 & 584.35 & 0.00 & 0.43 & 0.57 & 0.00 & 0.00 & 0.00 \\
PENP-4-6 & 797.80 & 0.15 & 0.85 & 0.00 & 0.00 & 0.00 & 0.00 \\
PENP-4-7 & 303.88 & 0.68 & 0.00 & 0.31 & 0.00 & 0.00 & 0.00 \\
PENP-4-8 & 314.07 & 0.67 & 0.00 & 0.33 & 0.00 & 0.00 & 0.00 \\
PENP-4-9 & 1183.76 & 0.43 & 0.56 & 0.00 & 0.01 & 0.00 & 0.00 \\
PENP-5-1 & 161.81 & 0.64 & 0.00 & 0.00 & 0.00 & 0.36 & 0.00 \\
PENP-5-2 & 401.66 & 0.28 & 0.00 & 0.14 & 0.00 & 0.58 & 0.00 \\
PENP-6-1 & 577.46 & 0.67 & 0.00 & 0.18 & 0.15 & 0.00 & 0.00 \\
PENP-BS-1 & 596.84 & 0.11 & 0.17 & 0.39 & 0.23 & 0.09 & 0.00 \\
PENP-BS-2 & 271.69 & 0.11 & 0.00 & 0.51 & 0.08 & 0.29 & 0.00 \\
PENP-BS-3 & 134.70 & 0.30 & 0.00 & 0.13 & 0.46 & 0.11 & 0.00 \\
PENP-BS-4 & 214.20 & 0.38 & 0.00 & 0.43 & 0.01 & 0.18 & 0.00 \\
PENP-BS-5 & 369.78 & 0.00 & 0.00 & 1.00 & 0.00 & 0.00 & 0.00 \\
PENP-BS-6 & 478.35 & 0.00 & 0.09 & 0.91 & 0.00 & 0.00 & 0.00 \\

\end{longtable}

\subsection{Data management}\label{data-management}

A total of 12456 recordings were collected (see
Figure~\ref{fig-recs-collect}). From 2019 - 2021, data were transferred
via hard drive to the University of Alberta in Edmonton, where they are
redundantly stored on a server known as Cirrus. The recordings were
standardized to ensure adherence to the naming convention of
\texttt{LOCATION\_DATETIME}, such as
\texttt{PENP-1-1\_20230625\_053500.wav}. The remaining recordings (2022
- 2025) were directly uploaded to WildTrax by Parks Canada staff and can
be downloaded from the platform's Recording tab, accessible under Manage
\textgreater{} Download list of recordings.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{peinp_files/figure-pdf/fig-recs-collect-1.pdf}}

}

\caption{\label{fig-recs-collect}Ridgeplot of recordings collected for
each location over each survey year}

\end{figure}%

\subsection{Community data processing}\label{community-data-processing}

The principal goal for data processing was to describe the acoustic
community of species heard at locations while choosing a large enough
subset of recordings for analyses. To ensure balanced replication, for
each location and year surveyed, four randomly selected recordings were
processed for 3-minutes between the hours of 4:00 AM - 7:59 AM ideally
on four separate dates (see Table~\ref{tbl-loc-repl}). Four recordings
will ensure that we have the minimum number of samples for a simple
occupancy analysis (Darryl I. MacKenzie et al. (2002) and Darryl I.
MacKenzie et al. (2003)). Tags are made using count-removal (see
Farnsworth et al. (2002), Sólymos et al. (2018)) where tags are only
made at the time of first detection of each individual heard on the
recordings. In case a species was overly abundant a TMTT (`too many to
tag') flag was used (see Table~\ref{tbl-tmtt}). 0\% of the total tags
were TMTT but were subsequently converted to numeric using
\texttt{wildrtrax::wt\_replace\_tmtt}. We also verified that all tags
that were created were checked by a second observer (n = 1.13) to ensure
accuracy of detections (see Table~\ref{tbl-verified}). Amphibian
abundance was estimated at the time of first detection using the
\href{https://www.usgs.gov/centers/eesc/science/north-american-amphibian-monitoring-program}{North
American Amphibian Monitoring Program} with abundance of species being
estimated on the scale of ``calling intensity index'' (CI) of 1 - 3.
Mammals such as Red Squirrel, were also noted on the recordings. After
the data are processed in WildTrax, the
\href{https://abbiodiversity.github.io/wildrtrax/}{wildrtrax} package is
use to download the data into a standard format prepared for analysis.
The \texttt{wt\_download\_report} function downloads the data directly
to a R framework for easy manipulation (see
\href{https://abbiodiversity.github.io/wildrtrax/articles/apis.html}{wildrtrax
APIs}).

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0625}}
  >{\raggedright\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1389}}
  >{\raggedright\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0833}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1875}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0972}}
  >{\raggedright\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1181}}
  >{\raggedright\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0903}}
  >{\raggedright\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1042}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1181}}@{}}

\caption{\label{tbl-loc-repl}Example of tasks and unit replication}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
location
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
recording\_date\_time
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
task\_method
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
recording\_sample\_frequency
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
task\_duration
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
task\_is\_complete
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
observer
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
task\_comments
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
internal\_task\_id
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
PENP-6-1 & 2024-06-27 06:23:00 & 1SPT & 44100 & 180 & TRUE & Enid
Cumming & NA & 1694861 \\
PENP-1-5 & 2024-06-09 07:21:00 & 1SPT & 44100 & 180 & TRUE & Enid
Cumming & NA & 1694862 \\
PENP-5-2 & 2024-06-28 04:24:00 & 1SPT & 44100 & 180 & TRUE & Enid
Cumming & NA & 1694863 \\
PENP-1-5 & 2024-06-07 04:21:00 & 1SPT & 44100 & 180 & TRUE & Enid
Cumming & NA & 1694864 \\
PENP-2-4 & 2024-05-27 06:27:00 & 1SPT & 44100 & 180 & TRUE & Enid
Cumming & good recording & 1694865 \\
PENP-1-5 & 2024-06-08 05:21:00 & 1SPT & 44100 & 180 & TRUE & Enid
Cumming & NA & 1694866 \\

\end{longtable}

\begin{longtable}[]{@{}lrr@{}}

\caption{\label{tbl-verified}Proportion of tags verified}

\tabularnewline

\toprule\noalign{}
Tag is verified & Count & Proportion \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
FALSE & 2229 & 29.26 \\
TRUE & 5303 & 69.61 \\
NA & 86 & 1.13 \\

\end{longtable}

\begin{longtable}[]{@{}llll@{}}

\caption{\label{tbl-tmtt}TMTT tags}

\tabularnewline

\toprule\noalign{}
location & recording\_date\_time & species\_code & abundance \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
PENP-3-1 & 2024-05-20 05:33:00 & CANG & TMTT \\
PENP-3-4 & 2024-05-28 06:26:00 & CANG & TMTT \\
PENP-3-4 & 2024-05-28 07:26:00 & CANG & TMTT \\
PENP-3-4 & 2024-06-01 06:23:00 & CANG & TMTT \\
PENP-3-2 & 2025-07-17 07:37:00 & CANG & TMTT \\
PENP-3-2 & 2025-07-17 08:37:00 & CEDW & TMTT \\

\end{longtable}

\begin{longtable}[]{@{}ll@{}}

\caption{\label{tbl-bird-guilds}Common bird forest species guilds. For
nesting habitat; Ag = Agricultural, Be = Beach, Bo = Bog, CW =
Coniferous Woodlands, ES = Early Successional, MW = Mixed Woodlands, OW
= Open Woodlands, TSS = Treed/Shrubby Swamp, Ur = Urban. Species from
CW, MW, OW, TSS were used for analysis.}

\tabularnewline

\toprule\noalign{}
species\_common\_name & habitat\_nesting \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Alder Flycatcher & Treed/Shrubby Swamp \\
American Redstart & Mixed Woodlands \\
Baltimore Oriole & Open Woodlands \\
Bay-breasted Warbler & Coniferous woodland \\
Black-and-white Warbler & Mixed Woodlands \\
Black-backed Woodpecker & Coniferous woodland \\
Black-throated Blue Warbler & Mixed Woodlands \\
Black-throated Green Warbler & Coniferous woodland \\
Blackburnian Warbler & Coniferous woodland \\
Blackpoll Warbler & Coniferous woodland \\
Blue Jay & Open Woodlands \\
Blue-headed Vireo & Mixed Woodlands \\
Boreal Chickadee & Coniferous woodland \\
Brown Creeper & Coniferous woodland \\
Canada Jay & Coniferous woodland \\
Canada Warbler & Mixed Woodlands \\
Cape May Warbler & Coniferous woodland \\
Chestnut-sided Warbler & Mixed Woodlands \\
Chipping Sparrow & Open Woodlands \\
Common Nighthawk & Open Woodlands \\
Dark-eyed Junco & Coniferous woodland \\
Downy Woodpecker & Mixed Woodlands \\
Eastern Wood-Pewee & Open Woodlands \\
Fox Sparrow & Open Woodlands \\
Golden-crowned Kinglet & Coniferous woodland \\
Gray Catbird & Mixed Woodlands \\
Hairy Woodpecker & Mixed Woodlands \\
Hermit Thrush & Coniferous woodland \\
Lincoln's Sparrow & Treed/Shrubby Swamp \\
Magnolia Warbler & Mixed Woodlands \\
Mountain Bluebird & Open Woodlands \\
Mourning Warbler & Mixed Woodlands \\
Northern Flicker & Mixed Woodlands \\
Northern Parula & Open Woodlands \\
Orange-crowned Warbler & Open Woodlands \\
Philadelphia Vireo & Mixed Woodlands \\
Pileated Woodpecker & Mixed Woodlands \\
Pine Warbler & Coniferous woodland \\
Red-eyed Vireo & Mixed Woodlands \\
Ruby-crowned Kinglet & Coniferous woodland \\
Ruffed Grouse & Mixed Woodlands \\
Rusty Blackbird & Treed/Shrubby Swamp \\
Swainson's Thrush & Mixed Woodlands \\
Veery & Mixed Woodlands \\
Warbling Vireo & Mixed Woodlands \\
Western Wood-Pewee & Open Woodlands \\
Yellow-bellied Sapsucker & Mixed Woodlands \\
Yellow-rumped Warbler & Coniferous woodland \\

\end{longtable}

\subsection{Bank swallows}\label{bank-swallows}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{./assets/bans.png}}

}

\caption{Bank swallow (C) Environment and Climate Change Canada}

\end{figure}%

Visual scanning is the concept of visually examining spectrograms in
order to find a signal within an audio recording. Visual scanning can be
a useful processing method allowing trained users to process recordings
much faster than traditional listening. It has been used for detecting
different taxa (amphibians: Cameron et al. (2020), mammals: Garland et
al. (2020)) with comparable biological metrics, as well as helping to
maximize species detection in large acoustic monitoring data sets (Ware
et al. (2023)). WildTrax's project settings and dynamic spectrogram
settings in the processing interface allow users to upload many
recordings, while also allowing frequency-limited or time-limited
spectrograms. These changes are easily made by adjusting project
settings in WildTrax (see Figure~\ref{fig-project-dynamic}). Bank
Swallow (Riparia riparia) are federally listed as threatened in Canada
(see Government of Canada) and provincially. They produce distinctive,
broadband vocalizations that are readily identifiable on a spectrogram,
making them well-suited to visual scanning workflows.

ARUs were placed near ponds where Bank Swallow are known to forage and
roost, as these habitats may support pre-migratory staging aggregations
in late summer. Documenting pond use, and in particular the timing and
density of vocalizations during dawn and dusk periods, can inform
whether ARU deployments are capable of capturing acoustic signatures
consistent with roosting behaviour, such as sustained high call-rate
events associated with group entry or departure from wetland sites. All
targeted recordings were reviewed by a trained observer using visual
scanning, with human detections serving as the primary record of Bank
Swallow presence.

In 2025, we refined our processing approach using dynamic spectrogram
settings (see Figure~\ref{fig-project-dynamic}), constraining the
frequency range to the 95\% CI of Bank Swallow vocalizations (2000-7500
Hz) while expanding the time window (1x -\textgreater{} 2x), reducing
visual noise and expediting detection. To complement visual scanning and
further reduce false negatives, we evaluated two automated classifiers,
BirdNET v2.1 (Kahl et al. (2021)) and HawkEars v1.0.8 (Huus et al.
(2025)), against the human-verified detection record. Classifier outputs
were overlaid directly on spectrograms in WildTrax, allowing reviewers
to cross-reference detections and apply expert judgment where classifier
confidence was low. Precision-recall analysis was used to evaluate
classifier performance relative to the human record, providing a basis
for assessing whether either classifier could serve as a reliable
detection tool for this species and behaviour in future seasons. A
summary of total data collected and recordings analyzed are summarized
in \textbf{?@tbl-bans}.

To address the question of whether ARUs can detect roosting-associated
activity, detections were examined by year and site to account for
variation in deployment configuration across monitoring seasons. Call
counts per recording, rather than binary presence, were used to
characterize detection intensity during dawn (04:00--08:00) and dusk
(19:00--22:00) survey periods, the windows most likely to capture
pre-roost and post-roost vocalizations. Sites monitored in multiple
years under different configurations (e.g., Bowley Pond, where one unit
was deployed in 2023 and three units in 2025) were examined separately
to explore whether detector density affected detection rates or call
volume during these periods.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{assets/project-dynamic.png}}

}

\caption{\label{fig-project-dynamic}Dynamic spectrogram and project
settings in WildTrax}

\end{figure}%

\subsection{Automated recognition}\label{automated-recognition}

Automated recognition is a well-known process to help detect rare and
elusive species (Knight and Bayne (2019). Shonfield, Heemskerk, and
Bayne (2018)) as well as species that may have a low detectability by
collecting large data sets. In order to determine the presence of a few
key species-at-risk, we utilized automated recognizers and deployed them
across all the recordings in the 2019 data set. We constructed a
recognizer for Eastern Wood-Pewee (EAWP) and used three previously
constructed Wildlife Acoustics SongScope recognizers for Olive-sided
Flycatcher (OSFL), Rusty Blackbird (RUBL) and Canada Warbler (CAWA) to
detect for the presence of these species in the 2019 data set. Hits were
verified and true positives for presence at each location (recording
where the species was first positively detected) were uploaded to
WildTrax via the \texttt{wt\_songscope\_tags} function in
\texttt{wildrtrax} for verification.

\subsection{Analyses}\label{analyses}

Species richness, diversity and occupancy were calculated using the 43,
9 forest songbird monitoring locations (\texttt{PENP-}). We calculated
species richness as distinct species found at each location and year
surveyed (see Figure~\ref{fig-spp-rich-locs}), omitting species using
\texttt{wildrtrax::wt\_tidy\_species()} for abiotic, amphibians,
unknowns and insects. To determine if there were any changes to species
diversity, we used Shannon's diversity index (Shannon (1948)) over years
using \texttt{vegan::diversity(index="shannon")} (see
Figure~\ref{fig-shannon}).

For testing species occupancy, we selected locations with a minimum of
four dawn visits for each year across all five years, focusing on forest
obligate species for ecological relevance (see
Table~\ref{tbl-bird-guilds}). Utilizing a single-season single-species
occupancy model from Darryl I. MacKenzie et al. (2002), we calculated
the predicted occupancy of species at all locations surveyed in each
year across years. Site-specific covariates included the distance to
ocean edge (in meters) and the proportional area of each cover type from
the
\href{https://data.princeedwardisland.ca/Environment-and-Food/OD0144-Corporate-Landuse-Inventory-2010/tc7z-7rpy}{Prince
Edward Island 2010 Corporate Land Use Inventory} at 150 meter radius
surrounding the ARU categorized into anthropogenic (pavement, soy), open
(grass, sand dune, bare soil), deciduous (red maple, white birch, alder,
poplar) and conifer (white spruce, black spruce, balsam fir).
Observation covariates incorporated day of the year, hour, observer, and
a quadratic term for both day of year (\(doy^{2}\)) and hour
(\(hr^{2}\)). See Table~\ref{tbl-obvs-and-covs} for more information.
Despite variations in processing methodology between 2019 - 2021 (1SPM -
species-individual detected per minute, i.e.~repeat sampling each minute
for 3 minute) and subsequent years (2022 - 2025; 1SPT), we maintained
consistency by exclusively utilizing the time to the first detection of
individuals from the 1SPM recordings. Model predictions were generated,
with goodness-of-fit testing using methods from Darryl I. MacKenzie and
Bailey (2004) and the best model selected based on AIC and through
\texttt{MuMIn::dregde}, \texttt{MuMIn::get.models} and
\texttt{MuMIn::model.sel}. If more than one model existed, the average
model was used using \texttt{MuMIn::model.avg}. The final predictions
were then made and plotted over years and sorted by nesting guilds of
species into conifer, deciduous, treed / shrubby, wetlands and open.
Trends in species abundance were assessed using a normalized count,
calculated as the total species count divided by the number of surveyed
locations per year. We focused on a subset of species representative of
the forest songbird community: BTNW, BLBW, GCKI, YRWA, MAWA, BTBW, BHVI,
AMRE, REVI, MOWA, BLJA, ALFL, EAWP, WTSP, AMRO, COYE, NOPA, YEWA. To
evaluate temporal trends in abundance over the past six years, we
applied generalized linear mixed models (GLMMs) each species as well as
the total count of the species over the period.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Results}\label{results}

\subsection{Species richness and
diversity}\label{species-richness-and-diversity}

A total of 102 species were found across the seven years.
Figure~\ref{fig-spp-rich-locs} describes the relationship of species
richness for each location across survey year. Shannon's diversity was
stable based on results (see Figure~\ref{fig-shannon}).

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{peinp_files/figure-pdf/fig-spp-rich-locs-1.pdf}}

}

\caption{\label{fig-spp-rich-locs}Species richness at forest monitoring
locations across years}

\end{figure}%

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{peinp_files/figure-pdf/fig-shannon-1.pdf}}

}

\caption{\label{fig-shannon}Shannon diversity index over years}

\end{figure}%

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{peinp_files/figure-pdf/fig-spp-activity-1.pdf}}

}

\caption{\label{fig-spp-activity}Seasonal detection activity of most
commonly detected forest species}

\end{figure}%

\subsubsection{Proximity to ocean
effects}\label{proximity-to-ocean-effects}

Proximity to the ocean may influence avian species richness detected at
ARU stations through elevated ambient noise levels. Wave action and
wind-driven coastal noise can reduce the effective detection distance of
ARUs, potentially masking vocalizations and leading to systematic
underdetection at exposed coastal sites (Pijanowski et al. (2011)). To
examine whether distance to the nearest coastline was associated with
observed species richness, we compared species counts across monitoring
locations as a function of coast distance. Contrary to expectations,
distance to the nearest coastline showed no meaningful association with
species richness across ARU monitoring locations (see
Figure~\ref{fig-ocean-richness}). Species richness was highly variable
at all distances, ranging from approximately 3--32 species regardless of
coastal proximity, and the fitted regression line was nearly flat across
the full range of distances sampled (0-2, 200 m). This suggests that,
within PEINP, coastal noise does not appear to systematically suppress
acoustic detectability or species richness at the distances represented
by our monitoring network, though the majority of stations were
clustered within 500 m of the coastline, limiting inference at greater
distances.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{peinp_files/figure-pdf/fig-ocean-richness-1.pdf}}

}

\caption{\label{fig-ocean-richness}Relationship between distance to
coastline and species richness across ARU monitoring locations.}

\end{figure}%

\subsection{Trends in abundance over
time}\label{trends-in-abundance-over-time}

Most forest species showed slight increasing and decreasing trends, with
only functional gain with White-throated sparrows over the years as seen
in Table~\ref{tbl-normalized-count-mdm-year}. There were no significant
difference in the total abundance of species included in the analyses as
demonstrated in Figure~\ref{fig-annual-count}.

\begin{longtable}[]{@{}llrrrr@{}}

\caption{\label{tbl-normalized-count-mdm-year}Linear models of species
trends using normalized mean count per location}

\tabularnewline

\toprule\noalign{}
species\_code & term & estimate & std.error & statistic & p.value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
ALFL & (Intercept) & 21.30 & 64.98 & 0.33 & 0.76 \\
ALFL & year & -0.01 & 0.03 & -0.31 & 0.77 \\
AMRE & (Intercept) & -29.08 & 40.20 & -0.72 & 0.50 \\
AMRE & year & 0.02 & 0.02 & 0.76 & 0.48 \\
AMRO & (Intercept) & -35.43 & 34.78 & -1.02 & 0.36 \\
AMRO & year & 0.02 & 0.02 & 1.05 & 0.34 \\
BHVI & (Intercept) & -42.54 & 22.31 & -1.91 & 0.11 \\
BHVI & year & 0.02 & 0.01 & 1.96 & 0.11 \\
BLBW & (Intercept) & -46.79 & 18.10 & -2.59 & 0.05 \\
BLBW & year & 0.02 & 0.01 & 2.65 & 0.05 \\
BLJA & (Intercept) & -30.82 & 46.75 & -0.66 & 0.54 \\
BLJA & year & 0.02 & 0.02 & 0.68 & 0.52 \\
BTBW & (Intercept) & 141.59 & 104.17 & 1.36 & 0.27 \\
BTBW & year & -0.07 & 0.05 & -1.35 & 0.27 \\
BTNW & (Intercept) & -31.51 & 41.81 & -0.75 & 0.48 \\
BTNW & year & 0.02 & 0.02 & 0.78 & 0.47 \\
COYE & (Intercept) & -85.47 & 26.91 & -3.18 & 0.02 \\
COYE & year & 0.04 & 0.01 & 3.22 & 0.02 \\
EAWP & (Intercept) & -11.02 & 12.04 & -0.92 & 0.40 \\
EAWP & year & 0.01 & 0.01 & 1.00 & 0.36 \\
GCKI & (Intercept) & -36.94 & 33.71 & -1.10 & 0.32 \\
GCKI & year & 0.02 & 0.02 & 1.13 & 0.31 \\
MAWA & (Intercept) & -38.45 & 26.25 & -1.46 & 0.20 \\
MAWA & year & 0.02 & 0.01 & 1.51 & 0.19 \\
MOWA & (Intercept) & 0.64 & 36.86 & 0.02 & 0.99 \\
MOWA & year & 0.00 & 0.02 & 0.01 & 0.99 \\
NOPA & (Intercept) & 10.03 & 23.38 & 0.43 & 0.69 \\
NOPA & year & 0.00 & 0.01 & -0.38 & 0.72 \\
REVI & (Intercept) & 77.31 & 22.09 & 3.50 & 0.02 \\
REVI & year & -0.04 & 0.01 & -3.45 & 0.02 \\
WTSP & (Intercept) & -151.76 & 54.54 & -2.78 & 0.04 \\
WTSP & year & 0.08 & 0.03 & 2.81 & 0.04 \\
YEWA & (Intercept) & -121.76 & 53.74 & -2.27 & 0.07 \\
YEWA & year & 0.06 & 0.03 & 2.29 & 0.07 \\
YRWA & (Intercept) & -23.18 & 25.45 & -0.91 & 0.40 \\
YRWA & year & 0.01 & 0.01 & 0.95 & 0.38 \\

\end{longtable}

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{peinp_files/figure-pdf/fig-annual-count-1.pdf}}

}

\caption{\label{fig-annual-count}Annual count of medium-distance
migrants}

\end{figure}%

\subsection{Species occupancy}\label{species-occupancy}

We selected from those same 15 forested species to represent the forest
songbird community into 4 separate habitat nesting guilds (see
Table~\ref{tbl-bird-guilds} and Figure~\ref{fig-spp-occ}). Analysis of
species occupancy revealed diverse and varied changes across these
species. Analytically, many models were singular, and a few exhibited
overdispersion, likely due to low detections or a limited sample size of
spatial locations. Ubiquitous species such as Red-eyed Vireo,
Yellow-rumped Warbler, Magnolia Warbler and Northern Parula,
demonstrated stable site occupancy across the years. Generalist species
or those capable of capitalizing on utilizing mixed habitats,
exemplified by the Northern Parula, also maintained consistent occupancy
levels. There were notable breakpoints in the occupancy of certain
species: coniferous species, including the Black-throated Green Warbler,
Black-throated Blue Warbler, Blackburnian Warbler, Golden-crowned
Kinglet, and Mourning Warbler, experiencing declines in 2023.
Conversely, increases were observed in guilds of species that favor more
open or shrubby habitats, such as the Alder Flycatcher and American
Redstart. Thrushes (American Robin, Swainson's Thrush, Hermit Thrush)
had notably wavering occupancy throughout the years.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{peinp_files/figure-pdf/fig-spp-occ-1.pdf}}

}

\caption{\label{fig-spp-occ}Single-season occupancy models of common
forest songbird species}

\end{figure}%

\subsection{Bank swallows}\label{bank-swallows-1}

\begin{tcolorbox}[enhanced jigsaw, opacitybacktitle=0.6, leftrule=.75mm, toptitle=1mm, breakable, opacityback=0, rightrule=.15mm, left=2mm, arc=.35mm, coltitle=black, colback=white, colframe=quarto-callout-note-color-frame, colbacktitle=quarto-callout-note-color!10!white, bottomtitle=1mm, titlerule=0mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Note}, bottomrule=.15mm, toprule=.15mm]

Some of these analyses are still a work-in-progress. Check back soon for
updates and additional details.

\end{tcolorbox}

\begin{table}

\caption{\label{tbl-bans-sites}Summary of Bank Swallow ARU monitoring
sites within PEINP, 2021--2025. Hours collected reflect total recording
effort; hours analyzed reflect processed tasks only. Proportion analyzed
is calculated per site per year. BANS detections are the number of
unique detections of BANS within a recording under a count-removal
framework at the recording level.}

\centering{

\fontsize{10.0pt}{12.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}l|lllrrrr}
\toprule
 & Location ID & Site & Survey Period & Hours collected & Hours analyzed & \% analyzed & BANS detections \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{8}{>{\raggedright\arraybackslash}m{1\linewidth}}{\parbox{\linewidth}{{\bfseries \cellcolor[HTML]{F9F9F9}{2021}}}} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
 & PENP-BS-1 & Clarke's Pond & May 04 – Aug 15 & 71.8 & 5.6 & {\cellcolor[HTML]{E9EBF0}{\textcolor[HTML]{000000}{8}}} & {\cellcolor[HTML]{F7F7F7}{\textcolor[HTML]{000000}{0}}} \\ 
 & PENP-BS-2 & Stanhope & May 04 – May 11 & 33.8 & 1.6 & {\cellcolor[HTML]{EFF0F3}{\textcolor[HTML]{000000}{5}}} & {\cellcolor[HTML]{F7F7F7}{\textcolor[HTML]{000000}{0}}} \\ 
 & PENP-BS-3 & Gulf Shore Parkway & May 04 – May 10 & 35.0 & 1.9 & {\cellcolor[HTML]{EFF0F3}{\textcolor[HTML]{000000}{5}}} & {\cellcolor[HTML]{F7F7F7}{\textcolor[HTML]{000000}{0}}} \\ 
 & PENP-BS-4 & North Rustico & Aug 03 – Aug 15 & 37.0 & 5.4 & {\cellcolor[HTML]{DEE1EB}{\textcolor[HTML]{000000}{15}}} & {\cellcolor[HTML]{F7F7F7}{\textcolor[HTML]{000000}{0}}} \\ 
 & PENP-BS-5 & Blooming Point & Aug 03 – Aug 15 & 24.9 & 2.5 & {\cellcolor[HTML]{E6E8EF}{\textcolor[HTML]{000000}{10}}} & {\cellcolor[HTML]{F7F7F7}{\textcolor[HTML]{000000}{0}}} \\ 
\midrule 
Total & — & — & — & 202 & 17 & 8.6% & 0 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{8}{>{\raggedright\arraybackslash}m{1\linewidth}}{\parbox{\linewidth}{{\bfseries \cellcolor[HTML]{F9F9F9}{2022}}}} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
 & PENP-BS-1 & Clarke's Pond & May 16 – Aug 04 & 291.9 & 28.2 & {\cellcolor[HTML]{E6E8EF}{\textcolor[HTML]{000000}{10}}} & {\cellcolor[HTML]{F9EFE8}{\textcolor[HTML]{000000}{3}}} \\ 
\midrule 
Total & — & — & — & 292 & 28 & 10.0% & 3 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{8}{>{\raggedright\arraybackslash}m{1\linewidth}}{\parbox{\linewidth}{{\bfseries \cellcolor[HTML]{F9F9F9}{2023}}}} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
 & PENP-BS-6 & Bowley Pond & Jul 14 – Jul 30 & 100.2 & 5.0 & {\cellcolor[HTML]{EFF0F3}{\textcolor[HTML]{000000}{5}}} & {\cellcolor[HTML]{F8F2ED}{\textcolor[HTML]{000000}{2}}} \\ 
\midrule 
Total & — & — & — & 100 & 5 & 5.0% & 2 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{8}{>{\raggedright\arraybackslash}m{1\linewidth}}{\parbox{\linewidth}{{\bfseries \cellcolor[HTML]{F9F9F9}{2024}}}} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
 & PENP-BS-1-1 & Clarke's Pond & Aug 01 – Sep 25 & 164.8 & 8.5 & {\cellcolor[HTML]{EFF0F3}{\textcolor[HTML]{000000}{5}}} & {\cellcolor[HTML]{F8F2ED}{\textcolor[HTML]{000000}{2}}} \\ 
\midrule 
Total & — & — & — & 165 & 8 & 5.0% & 2 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{8}{>{\raggedright\arraybackslash}m{1\linewidth}}{\parbox{\linewidth}{{\bfseries \cellcolor[HTML]{F9F9F9}{2025}}}} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
 & BANS-BOW-E & Bowley Pond (East) & Jul 25 – Aug 12 & 103.8 & 13.5 & {\cellcolor[HTML]{E1E4EC}{\textcolor[HTML]{000000}{13}}} & {\cellcolor[HTML]{F4A460}{\textcolor[HTML]{000000}{31}}} \\ 
 & BANS-BOW-N & Bowley Pond (North) & Jul 25 – Aug 28 & 100.7 & 5.3 & {\cellcolor[HTML]{EFF0F3}{\textcolor[HTML]{000000}{5}}} & {\cellcolor[HTML]{FBD1B2}{\textcolor[HTML]{000000}{14}}} \\ 
 & BANS-BOW-W & Bowley Pond (West) & Jul 25 – Aug 28 & 134.5 & 6.8 & {\cellcolor[HTML]{EFF0F3}{\textcolor[HTML]{000000}{5}}} & {\cellcolor[HTML]{FBCCA8}{\textcolor[HTML]{000000}{16}}} \\ 
\midrule 
Total & — & — & — & 339 & 26 & 7.7% & 61 \\ 
\bottomrule
\end{tabular*}

}

\end{table}%

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{peinp_files/figure-pdf/fig-bans-bowley-doy-1.pdf}}

}

\caption{\label{fig-bans-bowley-doy}Bank Swallow detections at Bowley
Pond over the season, faceted by detector unit. Bars show total calls
detected per day.}

\end{figure}%

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{peinp_files/figure-pdf/fig-bans-ai-1.pdf}}

}

\caption{\label{fig-bans-ai}Performance of two acoustic classifiers on
the detection of Bank Swallow at the task level. Precision and recall
were evaluated based on detections by humans in the entire PEINP EI
Monitoring dataset.}

\end{figure}%

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Amphibians}\label{amphibians}

A total of 5 amphibians were detected: SPPE, AMTO, GRFG, BULL, MIFR. A
preliminary pattern of amphibian activity can be seen in
Figure~\ref{fig-spp-amphs-day} for Green Frog and Spring Peeper where
there were enough detections to generate activity patterns. Spring
peeper activity commenced much earlier than Green Frog although seasonal
patterns are consistent with the species' phenology (see Lovett (2013),
Ackleh et al. (2010)).

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{peinp_files/figure-pdf/fig-spp-amphs-day-1.pdf}}

}

\caption{\label{fig-spp-amphs-day}Seasonal and yearly activity plots for
Green Frog and Spring Peeper}

\end{figure}%

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Discussion}\label{discussion}

Considering the recent (2022) natural disturbance effects seen in the
Park, species richness and diversity stayed relatively stable.
Individuals nesting in conifer dominant stands likely moved to more
suitable habitat outside the park, suggesting the potential utility of
metapopulation analysis through passive acoustic monitoring outside of
the park via citizen science participation.

Further analysis may utilize dynamic occupancy models (Darryl I.
MacKenzie et al. (2009)), multi-species multi-season occupancy models
(Devarajan, Morelli, and Tenan (2020)), or community shifts (Oksanen et
al. (2010)) to describe richness and diversity while accounting for
decreases in species that may rely on specific habitat structures within
the park. Additional geospatial assets could improve the accuracy of
modelling apporaches as well. Nevertheless, this study demostrates the
efficacy of autonomous recording units (ARUs) as a powerful tool for
monitoring climatic and habitat shifts with a relatively low sample size
and area coverage. As Avian species within the Park forest demonstrate a
non-uniform distribution relative to habitat, the following
recommendations for optimizing the efficiency and reliability of the ARU
program include:

\begin{itemize}
\tightlist
\item
  Prioritizing monitoring of historical locations, particularly
  emphasizing repeats at PENP-3-1, PENP-3-4, PENP-3-6, PENP-4-2 as
  baselines for evaluating ecological changes over time.
\item
  Adjusting monitoring times to dawn and dusk and extending deployment
  periods to 4-7 days between May 15 and July 15 to maximize
  vocalizations during peak activity periods.
\item
  Regular servicing of ARUs, focusing on testing microphone sensitivity
  degradation to ensure optimal functionality, data reliability, and
  longevity.
\item
  Continuing high-quality verification of tags to create annotated
  datasets for building and automating classifiers within WildTrax.
\item
  Data publication WildTrax can further the dissemination of information
  and participation of others in the park network
\end{itemize}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-abrahms2023climate}
Abrahms, Briana, Neil H Carter, TJ Clark-Wolf, Kaitlyn M Gaynor, Erik
Johansson, Alex McInturff, Anna C Nisi, Kasim Rafiq, and Leigh West.
2023. {``Climate Change as a Global Amplifier of Human--Wildlife
Conflict.''} \emph{Nature Climate Change} 13 (3): 224--34.

\bibitem[\citeproctext]{ref-ackleh2010measuring}
Ackleh, Azmy S, Jacoby Carter, Lauren Cole, Tom Nguyen, Jay Monte, and
Claire Pettit. 2010. {``Measuring and Modeling the Seasonal Changes of
an Urban Green Treefrog (Hyla Cinerea) Population.''} \emph{Ecological
Modelling} 221 (2): 281--89.

\bibitem[\citeproctext]{ref-allan2017recent}
Allan, James R, Oscar Venter, Sean Maxwell, Bastian Bertzky, Kendall
Jones, Yichuan Shi, and James EM Watson. 2017. {``Recent Increases in
Human Pressure and Forest Loss Threaten Many Natural World Heritage
Sites.''} \emph{Biological Conservation} 206: 47--55.

\bibitem[\citeproctext]{ref-vis-scan-amphs}
Cameron, J., A. Crosby, C. Paszkowski, and E. Bayne. 2020. {``Visual
Spectrogram Scanning Paired with an Observation--Confirmation Occupancy
Model Improves the Efficiency and Accuracy of Bioacoustic Anuran
Data.''} \emph{Canadian Journal of Zoology} 98 (11): 733--42.
\url{https://doi.org/10.1139/cjz-2020-0103}.

\bibitem[\citeproctext]{ref-devarajan2020multi}
Devarajan, Kadambari, Toni Lyn Morelli, and Simone Tenan. 2020.
{``Multi-Species Occupancy Models: Review, Roadmap, and
Recommendations.''} \emph{Ecography} 43 (11): 1612--24.

\bibitem[\citeproctext]{ref-fahrig2003effects}
Fahrig, Lenore. 2003. {``Effects of Habitat Fragmentation on
Biodiversity.''} \emph{Annual Review of Ecology, Evolution, and
Systematics} 34 (1): 487--515.

\bibitem[\citeproctext]{ref-farnsworth2002removal}
Farnsworth, George L, Kenneth H Pollock, James D Nichols, Theodore R
Simons, James E Hines, and John R Sauer. 2002. {``A Removal Model for
Estimating Detection Probabilities from Point-Count Surveys.''}
\emph{The Auk} 119 (2): 414--25.

\bibitem[\citeproctext]{ref-aru-vs-cams-wolves}
Garland, Laura, Andrew Crosby, Richard Hedley, Stan Boutin, and Erin
Bayne. 2020. {``Acoustic Vs. Photographic Monitoring of Gray Wolves
({Canis lupus}): A Methodological Comparison of Two Passive Monitoring
Techniques.''} \emph{Canadian Journal of Zoology} 98 (3): 219--28.
\url{https://doi.org/10.1139/cjz-2019-0081}.

\bibitem[\citeproctext]{ref-hanski2011habitat}
Hanski, Ilkka. 2011. {``Habitat Loss, the Dynamics of Biodiversity, and
a Perspective on Conservation.''} \emph{Ambio} 40 (3): 248--55.

\bibitem[\citeproctext]{ref-huus2025hawkears}
Huus, Jan, Kevin G Kelly, Erin M Bayne, and Elly C Knight. 2025.
{``HawkEars: A Regional, High-Performance Avian Acoustic Classifier.''}
\emph{Ecological Informatics} 87: 103122.

\bibitem[\citeproctext]{ref-kahl2021birdnet}
Kahl, Stefan, Connor M Wood, Maximilian Eibl, and Holger Klinck. 2021.
{``BirdNET: A Deep Learning Solution for Avian Diversity Monitoring.''}
\emph{Ecological Informatics} 61: 101236.

\bibitem[\citeproctext]{ref-knight2019classification}
Knight, Elly C, and Erin M Bayne. 2019. {``Classification Threshold and
Training Data Affect the Quality and Utility of Focal Species Data
Processed with Automated Audio-Recognition Software.''}
\emph{Bioacoustics} 28 (6): 539--54.

\bibitem[\citeproctext]{ref-lemieux2011state}
Lemieux, Christopher J, Thomas J Beechey, Daniel J Scott, and Paul A
Gray. 2011. {``The State of Climate Change Adaptation in Canada's
Protected Areas Sector.''} \emph{The Canadian Geographer/Le G{é}ographe
Canadien} 55 (3): 301--17.

\bibitem[\citeproctext]{ref-lovett2013peepers}
Lovett, Gary M. 2013. {``When Do Peepers Peep? Climate and the Date of
First Calling in the Spring Peeper (Pseudacris Crucifer) in Southeastern
New York State.''} \emph{Northeastern Naturalist} 20 (2): 333--40.

\bibitem[\citeproctext]{ref-occu-fit}
MacKenzie, Darryl I., and Larissa L. Bailey. 2004. {``Assessing the Fit
of Site-Occupancy Models.''} \emph{Journal of Agricultural, Biological,
and Environmental Statistics} 9 (3): 300--318.
\url{http://www.jstor.org/stable/1400484}.

\bibitem[\citeproctext]{ref-imperfect-occu}
MacKenzie, Darryl I., James D. Nichols, James E. Hines, Melinda G.
Knutson, and Alan B. Franklin. 2003. {``ESTIMATING SITE OCCUPANCY,
COLONIZATION, AND LOCAL EXTINCTION WHEN a SPECIES IS DETECTED
IMPERFECTLY.''} \emph{Ecology} 84 (8): 2200--2207.
https://doi.org/\url{https://doi.org/10.1890/02-3090}.

\bibitem[\citeproctext]{ref-mackenzie2002estimating}
MacKenzie, Darryl I, James D Nichols, Gideon B Lachman, Sam Droege, J
Andrew Royle, and Catherine A Langtimm. 2002. {``Estimating Site
Occupancy Rates When Detection Probabilities Are Less Than One.''}
\emph{Ecology} 83 (8): 2248--55.

\bibitem[\citeproctext]{ref-mackenzie2009modeling}
MacKenzie, Darryl I, James D Nichols, Mark E Seamans, and RJ Gutiérrez.
2009. {``Modeling Species Occurrence Dynamics with Multiple States and
Imperfect Detection.''} \emph{Ecology} 90 (3): 823--35.

\bibitem[\citeproctext]{ref-mantyka2012interactions}
Mantyka-pringle, Chrystal S, Tara G Martin, and Jonathan R Rhodes. 2012.
{``Interactions Between Climate and Habitat Loss Effects on
Biodiversity: A Systematic Review and Meta-Analysis.''} \emph{Global
Change Biology} 18 (4): 1239--52.

\bibitem[\citeproctext]{ref-oksanen2010canonical}
Oksanen, Jari, Frank G Blanchet, Roeland Kindt, Pierre Legendre, Peter R
Minchin, Robert B O'Hara, Gavin L Simpson, et al. 2010. {``Canonical
Analysis of Principal Coordinates: A Useful Method of Constrained
Ordination for Ecology.''} \emph{Ecology} 92 (3): 597--611.
\url{https://doi.org/10.1890/10-0340.1}.

\bibitem[\citeproctext]{ref-pijankowski2011landscape}
Pijanowski, Bryan C., Luis J. Villanueva-Rivera, Sarah L. Dumyahn, Almo
Farina, Bernie L. Krause, Brian M. Napoletano, Stuart H. Gage, and Nadia
Pieretti. 2011. {``Soundscape Ecology: The Science of Sound in the
Landscape.''} \emph{BioScience} 61 (3): 203--16.
\url{https://doi.org/10.1525/bio.2011.61.3.6}.

\bibitem[\citeproctext]{ref-sattar2021review}
Sattar, Q, ME Maqbool, R Ehsan, S Akhtar, Q Sattar, ME Maqbool, R Ehsan,
and S Akhtar. 2021. {``Review on Climate Change and Its Effect on
Wildlife and Ecosystem.''} \emph{Open J Environ Biol} 6 (1): 008--14.

\bibitem[\citeproctext]{ref-shannon1948mathematical}
Shannon, Claude Elwood. 1948. {``A Mathematical Theory of
Communication.''} \emph{The Bell System Technical Journal} 27 (3):
379--423.

\bibitem[\citeproctext]{ref-aru-overview}
Shonfield, Julia, and Erin M Bayne. 2017. {``Autonomous Recording Units
in Avian Ecological Research: Current Use and Future Applications.''}
\emph{Avian Conservation \& Ecology} 12 (1).

\bibitem[\citeproctext]{ref-shonfield2018utility}
Shonfield, Julia, Sarah Heemskerk, and Erin M Bayne. 2018. {``Utility of
Automated Species Recognition for Acoustic Monitoring of Owls.''}
\emph{Journal of Raptor Research} 52 (1): 42--55.

\bibitem[\citeproctext]{ref-time-removal}
Sólymos, Péter, Steven M. Matsuoka, Steven G. Cumming, Diana Stralberg,
Patricia Fontaine, Fiona K. A. Schmiegelow, Samantha J. Song, and Erin
M. Bayne. 2018. {``{Evaluating time-removal models for estimating
availability of boreal birds during point count surveys: Sample size
requirements and model complexity}.''} \emph{The Condor} 120 (4):
765--86. \url{https://doi.org/10.1650/CONDOR-18-32.1}.

\bibitem[\citeproctext]{ref-lots-of-pam}
Sugai, Larissa Sayuri Moreira, Thiago Sanna Freire Silva, Jr Ribeiro
José Wagner, and Diego Llusia. 2018. {``{Terrestrial Passive Acoustic
Monitoring: Review and Perspectives}.''} \emph{BioScience} 69 (1):
15--25. \url{https://doi.org/10.1093/biosci/biy147}.

\bibitem[\citeproctext]{ref-arus-mics}
Turgeon, Patrick, Steven L. Van Wilgenburg, and Kiel L. Drake. 2017.
{``Microphone Variability and Degradation: Implications for Monitoring
Programs Employing Autonomous Recording Units.''} \emph{Avian
Conservation and Ecology} 12.
\url{https://api.semanticscholar.org/CorpusID:89959184}.

\bibitem[\citeproctext]{ref-all-the-scans}
Ware, Lena, C. Lisa Mahon, Logan McLeod, and Jean-François Jetté. 2023.
{``Artificial Intelligence (BirdNET) Supplements Manual Methods to
Maximize Bird Species Richness from Acoustic Data Sets Generated from
Regional Monitoring.''} \emph{Canadian Journal of Zoology} 101 (12):
1031--51. \url{https://doi.org/10.1139/cjz-2023-0044}.

\end{CSLReferences}




\end{document}
